### ISSUE TITLE
Want to understand why there is no previous link for pagination?

### ISSUE THREAD

**Issue by ajaysharmamca** [NewMotion/ocpi-endpoints#50]
OCPI Specification refered.
Link Link to the ‘next’ page should be provided, when this is NOT the last page. The Link
should also contain any filters present in the original request. See example below
ink: <https://www.server.com/ocpi/cpo/2.0/cdrs/?offset=200&limit=50>; rel="next"

**Comment by poohsen** [comment]
the reason is that this is an API for machine-to-machine communication. The pagination is there to enable a cap on the message size and prevent timeouts and buffer overruns.

Links to the previous page make sense in APIs meant for building UIs which are then used by humans who might want to go back one page.
